import{g as l,p as L}from"./assets/quote-ce423603.js";import{i as n}from"./assets/vendor-a0f761d2.js";const a={getInfo(t){n.info({title:"Hello",message:t})},getErrorInfo(t){n.error({title:"Error",message:t})},getSuccessInfo(t){n.success({title:"OK",message:t})}};function u(t,e){const s=t.map(({filter:y,imgUrl:b,name:m})=>`
      <li class="lists js-list">
      <img src="${b}" alt="${m}"class="pic">
      <div class="position-text">
      <h2 class="muscles-title">${m}</h2>
      <p class="filter-title">${y}</p>
      </div>
      </li>`).join("");return e.insertAdjacentHTML("beforeend",s),s}const r=document.querySelector(".js-gallery"),o=document.querySelector(".js-buttonMuscles"),i=document.querySelector(".js-buttonBodyparts"),c=document.querySelector(".js-buttonEquipment");o.addEventListener("click",g);i.addEventListener("click",h);c.addEventListener("click",E);f();async function f(){i.classList.remove("active"),c.classList.remove("active"),o.classList.add("active");const e=(await l({filter:"Muscles",typeFilter:"filters"}).then(({data:s})=>s).catch(s=>a.getErrorInfo("Unfortunately, no results were found. You may want to consider other search options to find the exercise you are looking for. Our range is wide and you have the opportunity to find more options that suit your needs."))).results;r.innerHTML=u(e,r)}function g(){f()}async function h(){i.classList.add("active"),o.classList.remove("active"),c.classList.remove("active");const e=(await l({filter:"Body parts",typeFilter:"filters"})).data.results;r.innerHTML=u(e,r)}async function E(){c.classList.add("active"),(o.classList.contains("active")||i.classList.contains("active"))&&(o.classList.remove("active"),i.classList.remove("active"));const e=(await l({filter:"Equipment",typeFilter:"filters"})).data.results;r.innerHTML=u(e,r)}const M=/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/,d=document.querySelector(".footer-subscription-form"),p=document.querySelector(".footer-subscription-input"),v="feedback-subscribe-state",S=async t=>{t.preventDefault();const e=p.value.trim();if(!M.test(e))a.getErrorInfo("Enter the correct email!");else{try{await L({userEmail:{email:e},typeFilter:"subscription"}),a.getSuccessInfo("Successful subscription!")}catch{a.getErrorInfo("The user with this address is already subscribed!")}localStorage.removeItem(v),d.reset()}};d.addEventListener("submit",S);d.addEventListener("input",t=>{const e=p.value.trim(),s=JSON.stringify({footerEmail:e});localStorage.setItem(v,s)});
//# sourceMappingURL=commonHelpers2.js.map
